### ISSUE TITLE
WP 6 - (warning not error) strings can't be parsed as xml

### ISSUE THREAD

**Issue by emilse-webdev** [WebDevStudios/WP-Contributions#24]
![image](https://user-images.githubusercontent.com/104102110/172918131-27e76d70-19ba-4c1d-9c2c-4ff5b1408ef1.png)

Just something from the log, it's not an issue

**Comment by tw2113** [comment]
This should be fixed as part of https://github.com/WebDevStudios/WP-Contributions/pull/30, since this looks to be the Codex count value that strangely seemed to rely on connectivity to the internet and also XML in general.

This got switched to JSON and should hopefully be doing better with caching.
